-- Modificacion TAbla Productos
ALTER TABLE  `Productos` ADD  `Imagen` VARCHAR( 200 ) NOT NULL AFTER  `Descripcion` ;
-- ***********************************************************************************

-- MySQL Script generated by MySQL Workbench
-- 07/09/16 20:12:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema noroeste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema noroeste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `noroeste` DEFAULT CHARACTER SET utf8 ;
USE `noroeste` ;

-- -----------------------------------------------------
-- Table `noroeste`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noroeste`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noroeste`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noroeste`.`Productos` (
  `idProductos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Codigo` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProductos`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC),
  INDEX `fk_Productos_Categoria_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Productos_Categoria`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `noroeste`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noroeste`.`Tipo_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noroeste`.`Tipo_Productos` (
  `idTipo_Productos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_Productos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noroeste`.`Productos_Relacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noroeste`.`Productos_Relacion` (
  `idProductos_Relacion` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Tipo_Productos_idTipo_Productos` INT NOT NULL,
  PRIMARY KEY (`idProductos_Relacion`),
  INDEX `fk_Productos_Relacion_Productos1_idx` (`Productos_idProductos` ASC),
  INDEX `fk_Productos_Relacion_Tipo_Productos1_idx` (`Tipo_Productos_idTipo_Productos` ASC),
  CONSTRAINT `fk_Productos_Relacion_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `noroeste`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Relacion_Tipo_Productos1`
    FOREIGN KEY (`Tipo_Productos_idTipo_Productos`)
    REFERENCES `noroeste`.`Tipo_Productos` (`idTipo_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `noroeste`.`Sub_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noroeste`.`Sub_Categoria` (
  `idSub_Categoria` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idSub_Categoria`),
  INDEX `fk_Sub_Categoria_Categoria1_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Sub_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `noroeste`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
